### ISSUE TITLE
Bold text is not shown as bold when committing changes to journal entries or items.

### ISSUE THREAD

**Issue by ProtonCrosser** [vkdolea/age-system#59] opened 2021-06-22 21:53 UTC
With the new font when populating text in journal entries, items, or other entities items that are made bold only show as bold when the text editor is active. Once saving changes the text is not shown as bold. Opening the editor shows the bold text as bold once again. See item (talent) example attached. 
<img width="403" alt="Screen Shot 2021-06-22 at 5 48 06 PM" src="https://user-images.githubusercontent.com/86327660/123004507-ad33e280-d382-11eb-963a-6df2f342788f.png">
<img width="403" alt="Screen Shot 2021-06-22 at 5 48 14 PM" src="https://user-images.githubusercontent.com/86327660/123004513-b0c76980-d382-11eb-8dfa-70b0483f4334.png">

Edit: Using Foundry 0.8.7. | Age System (Unofficial) 0.7.6

**Comment by vkdolea** [comment] 2021-06-22 22:39
I am not able to replicate this failure
![image](https://user-images.githubusercontent.com/66521243/123008210-da878d00-d390-11eb-9752-dcfb0582fcd0.png)
Maybe it is a module issue? Should I follow some specific steps to reproduce this issue?

**Comment by ProtonCrosser** [comment] 2021-06-23 01:29
I am unsure if there is anything specific to steps to reproduce. Creating a new item and then either typing manually or pasting in copied text, then changing text to bold. I discovered this when creating talents for Modern Age and was bolding the text for ability tests.

I tested the issue with all modules deactivated before reporting so I do not think there is a conflict on that front. I verified my results after your reply. I also just created a new world, no modules and just the system and then proceeded to test the issue and I achieve the same results of no bold text shown. I have not adjusted any settings in this new world.

Not sure how helpful this response will be. It is not a deal breaker by any stretch and I'll keep poking around seeing as you can reproduce but not sure what the cause could be. If you think of anything or discover anything to try, I will happily test on my end.

**Comment by vkdolea** [comment] 2021-06-23 11:42
I think it is based on the brower/software used to run FoundryVTT. I identified a possible cause and I expect I to be fixed on the next release. I will keep this issue open and I'll follow up with you after releasing the next version.

**Comment by ProtonCrosser** [comment] 2021-06-23 21:11
Sounds good. Thanks for looking into this and I've mentioned it before but I do appreciate the effort and time you put into this system.

**Comment by vkdolea** [comment] 2021-06-25 13:23
This is now updated on version 0.7.7. Could you please confirm if the problem is now solved?

**Comment by vkdolea** [comment] 2021-06-28 13:58
I consider it closed. By give a heads up if the problem is not solved. :-)

**Closed by vkdolea** 2021-06-28 13:58 UTC

**Comment by ProtonCrosser** [comment] 2021-06-29 18:19
Sorry for the delay in getting back to you. The fix seems to have do it and things are now working as expected. Thanks for your help and quick action.
